
spring:
  application:
    name: "gatewayserver"


  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          #enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

  info:
    app:
      name: "gatewayserver"
      description: "Eazy bank gateway server application"
      version: "1.0.0"

  logging:
    level:
      com:
        eazybytes:
          gatewayserver: DEBUG