services:
  accountsdb:
#    image: mysql
    container_name: accountsdb
    ports:
      - "3307:3306"

    environment:

      MYSQL_DATABASE: accountsdb

    extends:
      file: common-config.yml
      service: microservice-db-config


  loansdb:
#    image: mysql
    container_name: loanssdb
    ports:
      - "3308:3306"

    environment:

      MYSQL_DATABASE: loansdb

    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
#    image: mysql
    container_name: cardsdb
    ports:
      - "3309:3306"
#    healthcheck:
#      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
#      timeout: 10s
#      retries: 10
#      interval: 10s
#      start_period: 10s
    environment:
#      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb

    extends:
      file: common-config.yml
      service: microservice-db-config


#  rabbit:
#    image: rabbitmq:4.0-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  configserver:
    image: "shrutipuri1301/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "shrutipuri1301/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"

    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "shrutipuri1301/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"

    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "shrutipuri1301/cards:s7"
    container_name: cards-ms
    ports:
      - "9001:9001"
#    depends_on:
#      configserver:
#        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  shrutipuri1301:
    driver: "bridge"



#services:
#  rabbit:
#    image: rabbitmq:4.0-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_ports_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service
#
#  configserver:
#    image: "shrutipuri1301/configserver:s6"
#    container_name: configserver-ms
#    ports:
#      - "8071:8071"
#    depends_on:
#       rabbit:
#         condition: service_healthy
#
#    healthcheck:
#      test: "curl --fail --slient localhost:8071/actuator/health/readiness|grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#
#    extends:
#      file:  common-config.yml
#      service: microservice-base-config
#
#  accounts:
#    image: "shrutipuri1301/accounts:s6"
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#
#    environment:
#
#      SPRING_APPLICATION_NAME: "accounts"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  loans:
#    image: "shrutipuri1301/loans:s6"
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#
#    environment:
#       SPRING_APPLICATION_NAME: "loans"
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config
#
#  cards:
#    image: "shrutipuri1301/cards:s6"
#    container_name: cards-ms
#    ports:
#      - "9001:9001"
#    environment:
#
#      SPRING_APPLICATION_NAME: "cards"
#    extends:
#        file: common-config.yml
#        service: microservice-configserver-config
#
#networks:
#   shrutipuri1301:
#     driver: "bridge"
#
#
#
#
