server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

   #we need to enable the actuator endpoints that will
   #allow the refreshing the properties at runtime
management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      shutdown:
        enabled: true

      health:
        probes:
          enabled: true
    info:
      env:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



info:
  app:
    name: "loans"
    description: "EazyBank Loans related API's"
    version: "1.0.0"
  metrics :
    tags:
      application : ${spring.application.name}
logging:
    level:
      com:
        eazyByte:
           loans: DEBUG
    pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"



#loans:
#  message: "Welcome to EazyBank Loans related API'S"
#  contactDetails:
#    name: "Amaal Grega -Developer"
#    email: "amaal@eazyBank.com"
#  onCallSupport:
#    -(452)456-2176
#    -(546)764-8934