server:
  port: 9001

spring:
  application:
    name: "cards"

  profiles:
    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#    enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: root
    password: root
    enabled: true
  sql:
    init:
       mode: always

    jpa:
     show-sql: true


  config:
    import: "optional:configserver:http://localhost:8071/"


  #we need to enable the actuator endpoints that will
  #allow the refreshing the properties at runtime
management:
    endpoints:
      web:
        exposure:
          include: "*"
#
#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"
#  config:
#    import:
#      - "application_prod.yml"
#      - "application_qa.yml"
#
#  profiles:
#    active:
#      "qa"
#
#build:
#  version: "3.0"
#
#cards:
#  message: "Welcome to EazyBank cards related local API'S"
#  contactDetails:
#    name: "Dragos Lech-Developer"
#    email: "draqos@eazyBank.com"
#  onCallSupport:
#    -(666)265-3765
#    -(666)734-8371
